### ISSUE TITLE
Running in a non node server

### ISSUE THREAD

**Issue by wheresrhys** [steveworkman/grunt-yslow-test#2]
Hello,

I had a hell of a job getting this to work for a server not started within node, but eventually figured it out and here's my solution. Could be a valuable addition to the docs? http://stackoverflow.com/questions/19787805/using-grunt-and-phantomjs-with-a-jetty-server/19794250#19794250 (although this example is for jetty it should work regardless of what the server's running on)

**Comment by steveworkman** [comment]
Thanks for your efforts, I'll add it to the docs
